Add Read overloads for passing in buffer
badcel/HidApi.Net pull request #102
Opened 2024-08-11 18:42 UTC by TimonLukas

Implements #101

Warning: I did tested this only briefly (with a short bit of temporary code in `HidApi.Tester`). Can you recommend a good way to test it beyond that?

The method signatures had to slightly change compared to what we last discussed in the issue:

```csharp
public interface IDevice {
    ReadOnlySpan<byte> Read(int maxLength);
    int Read(Span<byte> buffer);
    ReadOnlySpan<byte> ReadTimeout(int maxLength, int milliseconds);
    int ReadTimeout(Span<byte> buffer, int milliseconds);
}
```

As the `Read` might not fill the whole buffer, the new overloads have to return the read length. I believe this is another good reason to leave the previous signatures intact, as they prevent this mistake.

The overloads caused a warning for the doc comment with `<see cref="Read">` - I fixed it by enumerating both signatures (so the references work again in the IDE), but I'm not sure this is the best solution.

2024-08-11 21:02 UTC, badcel requested changes
This looks already pretty good I added some remarks for small improvements.

Unfortunately I don't have devices to test this too. A detailed look must be sufficient.

If you have done the changes please squash all your changes into one commit to avoid having several commits for such a minimal change.

2024-08-11 21:18 UTC, TimonLukas commented
There, now it's clean. Sorry for the hasty mistakes!

2024-08-12 15:00 UTC, badcel commented
The code is not free of obsolete whitespaces, this is why the build fails. Please run `dotnet format` in the `src` folder to fix the issue automatically.

Please amend your changes to the last commit to avoid an additional commit.

2024-08-12 16:18 UTC, badcel approved these changes

2024-08-12 16:19 UTC, merged